---
- name: Cleanup Vault | Remove Docker
  become: true
  become_user: "{{ rv_hashicorp_vault_os_user }}"
  community.docker.docker_container:
    name: "{{ rv_hashicorp_vault_os_docker_name }}"
    state: absent

- name: Cleanup Vault | Remove Crop job
  ansible.builtin.cron:
    user: "{{ rv_hashicorp_vault_os_user }}"
    name: "{{ rv_hashicorp_vault_os_cron_job_name }}"
    state: absent

- name: Cleanup Vault | Remove Cron Setup Directory
  ansible.builtin.file:
    path: "{{ rv_hashicorp_vault_post_install_action_setup_auto_unseal_cron_dir }}"
    state: absent

- name: Cleanup Vault | Remove Init Directory
  ansible.builtin.file:
    path: "{{ rv_hashicorp_vault_post_install_action_initialize_secrets_directory }}"
    state: absent

- name: Cleanup Vault | Remove Data Directory
  ansible.builtin.file:
    path: "{{ rv_hashicorp_vault_os_data_directory }}"
    state: absent
