---
- name: Get Certificate Ownca | Certificate To Be Created | When Certificate Content Not Present
  when: not rv_getcert_to_be_created
  ansible.builtin.set_fact:
    rv_getcert_to_be_created: >-
      {{
        ( not rv_getcert_certificate_content is defined )
        or
        ( rv_getcert_certificate_content | length < 2 )
      }}
    rv_getcert_to_be_created_reason: "When Certificate Content Not Present"

- name: Get Certificate Ownca | Certificate To Be Created | Get Certificate Old Information
  when: not rv_getcert_to_be_created
  community.crypto.x509_certificate_info:
    content: "{{ rv_getcert_certificate_content }}"
    valid_at:
      one_day_after: "+1d"
  register: rv_getcert_tmp_certificate_content_x509_info
  ignore_errors: true

- name: Get Certificate Ownca | Certificate To Be Created | Existing Certificate is Invalid
  when: not rv_getcert_to_be_created
  ansible.builtin.set_fact:
    rv_getcert_to_be_created: >-
      {{ rv_getcert_tmp_certificate_content_x509_info.failed is defined
      and
      rv_getcert_tmp_certificate_content_x509_info.failed
      }}
    rv_getcert_to_be_created_reason: "Existing Certificate is Invalid"

- name: Get Certificate Ownca | Certificate To Be Created | Get Issuer Information
  when: not rv_getcert_to_be_created
  community.crypto.x509_certificate_info:
    content: "{{ rv_getcert_ownca_certificate_content }}"
    valid_at:
      not_crossed_issuer: "+{{ rv_getcert_validity_days }}d"
  register: rv_getcert_tmp_owca_certificate_content_x509_info

- name: Get Certificate Ownca | Certificate To Be Created | Authority Key Identifier Mismatch, Existing Certificate is not signed by OwnCA
  when: not rv_getcert_to_be_created
  ansible.builtin.set_fact:
    rv_getcert_to_be_created: >-
      {{ rv_getcert_tmp_certificate_content_x509_info.authority_key_identifier
      !=
      rv_getcert_tmp_owca_certificate_content_x509_info.subject_key_identifier }}
    rv_getcert_to_be_created_reason: "Authority Key Identifier Mismatch, Existing Certificate is not signed by OwnCA"

- name: Get Certificate Ownca | Certificate To Be Created | Certificate Expired
  when: not rv_getcert_to_be_created
  ansible.builtin.set_fact:
    rv_getcert_to_be_created: "{{ not rv_getcert_tmp_certificate_content_x509_info.valid_at.one_day_after }}"
    rv_getcert_to_be_created_reason: "Certificate Expired"
