---
- name: Get Certificate Ownca | Check Variables
  ansible.builtin.import_tasks:
    file: check_vars.yml

- name: Get Certificate Ownca | Set Values
  ansible.builtin.import_tasks:
    file: pre_set.yml

- name: Get Certificate Ownca | Create Certificate
  ansible.builtin.import_tasks:
    file: create.yml
