---
- name: Get Certificate Ownca | Create Private Key | Private Key
  community.crypto.openssl_privatekey_pipe:
    size: "{{ rv_getcert_private_key_size | default(omit) }}"
    passphrase: "{{ rv_getcert_private_key_password | default(omit) }}"
    content: "{{ rv_getcert_private_key_content | default(omit) }}"
    cipher: auto
  register: rv_getcert_private_key_content_create_new

- name: Get Certificate Ownca | Create Private Key | Private Key Set Fact
  when: rv_getcert_private_key_content_create_new.privatekey is defined
  ansible.builtin.set_fact:
    rv_getcert_private_key_content: "{{ rv_getcert_private_key_content_create_new.privatekey }}"
