---
- name: Get Certificate Ownca | Write Files | Write Certificate
  when:
    - rv_getcert_certificate_path is defined
    - rv_getcert_certificate_path | length > 0
  ansible.builtin.copy:
    content: "{{ rv_getcert_certificate_content }}"
    dest: "{{ rv_getcert_certificate_path }}"
    mode: "{{ rv_getcert_certificate_file_mode | default(omit, True) }}"
    owner: "{{ rv_getcert_certificate_owner | default(omit, True) }}"
    group: "{{ rv_getcert_certificate_group | default(omit, True) }}"

- name: Get Certificate Ownca | Write Files | Write Private Key
  when:
    - rv_getcert_private_key_path is defined
    - rv_getcert_private_key_path | length > 0
  ansible.builtin.copy:
    content: "{{ rv_getcert_private_key_content }}"
    dest: "{{ rv_getcert_private_key_path }}"
    mode: "{{ rv_getcert_private_key_file_mode | default(omit, True) }}"
    owner: "{{ rv_getcert_private_key_owner | default(omit, True) }}"
    group: "{{ rv_getcert_private_key_group | default(omit, True) }}"

- name: Get Certificate Ownca | Write Files | Write Certificate Full Chain
  when:
    - rv_getcert_certificatefullchain_path is defined
    - rv_getcert_certificatefullchain_path | length > 0
  ansible.builtin.copy:
    content: |+
      {{ rv_getcert_certificate_content | trim }}
      {{ rv_getcert_ownca_certificate_content }}
    dest: "{{ rv_getcert_certificatefullchain_path }}"
    mode: "{{ rv_getcert_certificatefullchain_file_mode | default(omit, True) }}"
    owner: "{{ rv_getcert_certificatefullchain_owner | default(omit, True) }}"
    group: "{{ rv_getcert_certificatefullchain_group | default(omit, True) }}"
