---
- name: Get Certificate Ownca | Write Files | Write Certificate
  when: rv_getcert_certificate_path is defined
  ansible.builtin.copy:
    content: "{{ rv_getcert_certificate_content }}"
    dest: "{{ rv_getcert_certificate_path }}"
    mode: "{{ rv_getcert_certificate_file_mode | default(omit) }}"

- name: Get Certificate Ownca | Write Files | Write Private Key
  when: rv_getcert_private_key_path is defined
  ansible.builtin.copy:
    content: "{{ rv_getcert_private_key_content }}"
    dest: "{{ rv_getcert_private_key_path }}"
    mode: "{{ rv_getcert_private_key_file_mode | default(omit) }}"
    owner: "{{ rv_getcert_private_key_owner | default(omit) }}"
    group: "{{ rv_getcert_private_key_group | default(omit) }}"
