---
- name: SSHD Hardening | Molecule | Converge
  hosts: all
  gather_facts: true
  tasks:
    - name: SSHD Hardening | Molecule | Converge | Include arpanrec.ssh_hardening
      become: true
      ansible.builtin.import_role:
        name: arpanrec.utilities.ssh_hardening

