---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Get user details
      ansible.builtin.command: "id {{ rv_user_add_username }}"
      register: userdetails
      changed_when: false

    - name: Print User Details
      ansible.builtin.debug:
        var: userdetails
