---
- name: Linux Patching | Install python3-pip and procps
  ansible.builtin.raw: apt-get update && apt-get install -y python3-pip procps
  register: rv_linux_patching_install_python_pip_result_raw
  changed_when: "'0 upgraded, 0 newly installed' not in rv_linux_patching_install_python_pip_result_raw.stdout_lines | last"

- name: Linux Patching | Install packages
  ansible.builtin.import_tasks: packages.yml

- name: Linux Patching | Date Time
  ansible.builtin.import_tasks: datetime.yml

- name: Linux Patching | Setup Host Network Information
  ansible.builtin.import_tasks: network.yml

- name: Linux Patching | Setup admin users
  ansible.builtin.import_tasks: user.yml
