---
- name: Linux Patching | Prerequisite | Gather Facts
  ansible.builtin.setup:

- name: Linux Patching | Prerequisite | Checking platform compatibility
  ansible.builtin.fail:
    msg: "{{ ansible_distribution }} is not supported by this role"
  when: ansible_distribution not in ['Debian']

- name: Linux Patching | Prerequisite | Get system 1 PID Details
  ansible.builtin.command: ps -p 1
  register: rv_linux_patching_tmp_one_pid_shell_result
  changed_when: false

- name: Linux Patching | Prerequisite | Assume system is not in systemd
  ansible.builtin.set_fact:
    rv_linux_patching_init_system_systemd:
      "{{ rv_linux_patching_tmp_one_pid_shell_result.stdout_lines[1] \
      | split(' ') | last == 'systemd' }}"
