---
rv_postman_install_path: "{{ ansible_facts.user_dir }}/.local/share/Postman"
rv_postman_xdg_icon_path: "{{ ansible_facts.user_dir }}/.local/share/applications/postman-userapps.desktop"
rv_postman_user_tmp_dir: "{{ ansible_facts.user_dir }}/.tmp/postman_app"
