---
- name: "Removing the user {{ rv_user_add_username }}"
  ansible.builtin.user:
    name: "{{ rv_user_add_username }}"
    state: absent
    remove: true

- name: "Removing the default group {{ rv_user_add_username }}"
  ansible.builtin.group:
    name: "{{ rv_user_add_username }}"
    state: absent

- name: "Removing sudoers file"
  ansible.builtin.file:
    path: "{{ rv_user_add_sudoers_file }}"
    state: absent
