---
dependency:
  name: galaxy
  enabled: false
  options:
    ignore-certs: false
    ignore-errors: false
    role-file: requirements.yml
    requirements-file: requirements.yml
driver:
  name: docker
platforms:
  - name: debian_role_util_scripts_default
    hostname: debian_role_util_scripts_default
    image: debian
    dockerfile: Dockerfile.j2
    pre_build_image: false
provisioner:
  name: ansible
  playbooks:
    converge: converge.yml
scenario:
  name: role.util_scripts.default
  converge_sequence:
    - converge
  test_sequence:
    - lint
    - syntax
    - create
    - converge
    - idempotence
    - destroy
verifier:
  name: ansible
lint: |
  set -e
  yamllint roles/util_scripts
  ansible-lint roles/util_scripts
  flake8 roles/util_scripts
