---
- name: Linux Patching | Molecule | Converge
  hosts: all
  become: false
  gather_facts: false
  any_errors_fatal: false
  tasks:
    - name: Linux Patching | Molecule | Converge | Role
      become: true
      become_method: su
      ansible.builtin.import_role:
        name: arpanrec.utilities.linux_patching
