---
- name: SSHD Hardening | Create config directory
  ansible.builtin.file:
    path: /etc/ssh/sshd_config.d
    state: directory
    mode: "0755"
    owner: root
    group: root
  notify:
    - SSH Hardening | Restart openssh server

- name: SSHD Hardening | Enable Firewall port
  community.general.ufw:
    port: "{{ rv_sshd_hardening_ssh_port }}"
    rule: allow
    state: enabled

- name: SSHD Hardening | Place config file
  ansible.builtin.template:
    src: templates/010-ssh-ansible.conf.j2
    dest: /etc/ssh/sshd_config.d/010-ssh-ansible.conf
    mode: "0755"
    owner: root
    group: root
  notify:
    - SSH Hardening | Restart openssh server
