---
# tasks file for ssh_hardening
- name: SSHD Hardening | Include Asserts
  ansible.builtin.import_tasks: 0000-pre-install-checks.yml

- name: SSHD Hardening | Include Variables
  ansible.builtin.import_vars: "vars-{{ ansible_os_family }}.yml"

- name: SSHD Hardening | Install Packages Archlinux
  ansible.builtin.import_tasks: "0100-install-{{ ansible_os_family }}.yml"

- name: Linux Patching | Enable UFW SSH Port
  community.general.ufw:
    rule: allow
    port: "{{ rv_sshd_hardening_ssh_port }}"
    proto: tcp
    state: enabled

- name: SSHD Hardening | Apply SSHD Settings
  ansible.builtin.import_tasks: 0200-ssh-security.yml
