---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: quay.io/centos/centos:stream8
    pre_build_image: true
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        rl_tef_api_debug_no_log: true
        rl_tef_org_name: ansible_molecule_run_test_arpanrec
        rl_tef_org_email: test@arpanrec.com
        rl_tef_api_collaborator_auth_policy: password
        rl_tef_workspaces:
          - rl_tef_workspace_name: test_workspace_1
            auto_apply: 0
            execution_mode: local
          - rl_tef_workspace_name: test_workspace_2
            auto_apply: 1
            execution_mode: remote
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
scenario:
  test_sequence:
    - lint
    - destroy
    - syntax
    - create
    - converge
    - idempotence
    - cleanup
    - destroy
